version: '2.1'

services:
  db:
    image: postgres
    healthcheck:
      test: exit 0
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=userInfo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
        - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  app:
    build: .
    image: agadient2018/ajgrepo:project1_authentication_service
    command: npm start
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432
      - NODE_ENV=test
    depends_on:
      db:
        condition: service_healthy
    links:
     - db
    ports:
     - 3000:3000